# Site
name: "Cuong Nguyen"
title: "Cuong Nguyen"
description: "A virtual proof that I'm awesome"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog-temp
google_analytics: 'UA-167420207-1'
disqus: 'cuongn'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:year-:month-:day-:title/

# Authors
authors:
  cuongn:
    name: CuongN
    display_name: Cuong Nguyen    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: cuonghapvn@gmail.com
    web: https://www.cuongn.com
    twitter: https://twitter.com/cuonghapvn
    description: "A developer | project manager | nice guy"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
